name: Build .net core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.100
    - name: Build
      run: build.cmd Release
      shell: cmd
    - name: Pack
      run: pack.cmd Release
      shell: cmd
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: |
          artifacts/packages/*.nupkg
